// ABOUTME: Unit tests for the keytun Web Crypto module.
// ABOUTME: Verifies key generation, ECDH key exchange, HKDF derivation, and AES-GCM encrypt/decrypt.
import { describe, it, expect } from 'vitest';
import { generateKeyPair, deriveSharedKey, encrypt, decrypt } from './keytun-crypto.js';

describe('keytun-crypto', () => {
  describe('generateKeyPair', () => {
    it('returns a private key and 32-byte public key', async () => {
      const kp = await generateKeyPair();
      expect(kp.privateKey).toBeDefined();
      expect(kp.publicKey).toBeInstanceOf(Uint8Array);
      expect(kp.publicKey.length).toBe(32);
    });

    it('generates distinct key pairs each call', async () => {
      const kp1 = await generateKeyPair();
      const kp2 = await generateKeyPair();
      expect(kp1.publicKey).not.toEqual(kp2.publicKey);
    });
  });

  describe('deriveSharedKey', () => {
    it('derives the same AES key on both sides of an exchange', async () => {
      const alice = await generateKeyPair();
      const bob = await generateKeyPair();

      const aliceKey = await deriveSharedKey(alice.privateKey, bob.publicKey);
      const bobKey = await deriveSharedKey(bob.privateKey, alice.publicKey);

      // Export both CryptoKeys to raw bytes for comparison
      const aliceRaw = new Uint8Array(await crypto.subtle.exportKey('raw', aliceKey));
      const bobRaw = new Uint8Array(await crypto.subtle.exportKey('raw', bobKey));

      expect(aliceRaw).toEqual(bobRaw);
    });

    it('derives a 256-bit AES-GCM key', async () => {
      const alice = await generateKeyPair();
      const bob = await generateKeyPair();

      const key = await deriveSharedKey(alice.privateKey, bob.publicKey);
      expect(key.algorithm.name).toBe('AES-GCM');
      const raw = await crypto.subtle.exportKey('raw', key);
      expect(raw.byteLength).toBe(32);
    });
  });

  describe('encrypt / decrypt round-trip', () => {
    it('decrypts to the original plaintext', async () => {
      const alice = await generateKeyPair();
      const bob = await generateKeyPair();
      const key = await deriveSharedKey(alice.privateKey, bob.publicKey);

      const plaintext = new TextEncoder().encode('hello keytun');
      const ciphertext = await encrypt(key, plaintext);
      const decrypted = await decrypt(key, ciphertext);

      expect(decrypted).toEqual(plaintext);
    });

    it('ciphertext is nonce (12 bytes) + encrypted data', async () => {
      const alice = await generateKeyPair();
      const bob = await generateKeyPair();
      const key = await deriveSharedKey(alice.privateKey, bob.publicKey);

      const plaintext = new Uint8Array([0x41]); // 'A'
      const ciphertext = await encrypt(key, plaintext);

      // 12 byte nonce + 1 byte plaintext + 16 byte GCM tag = 29
      expect(ciphertext.length).toBe(12 + 1 + 16);
    });

    it('produces different ciphertext each time (random nonce)', async () => {
      const alice = await generateKeyPair();
      const bob = await generateKeyPair();
      const key = await deriveSharedKey(alice.privateKey, bob.publicKey);

      const plaintext = new TextEncoder().encode('test');
      const ct1 = await encrypt(key, plaintext);
      const ct2 = await encrypt(key, plaintext);

      expect(ct1).not.toEqual(ct2);
    });

    it('fails to decrypt with wrong key', async () => {
      const alice = await generateKeyPair();
      const bob = await generateKeyPair();
      const eve = await generateKeyPair();

      const rightKey = await deriveSharedKey(alice.privateKey, bob.publicKey);
      const wrongKey = await deriveSharedKey(eve.privateKey, bob.publicKey);

      const ciphertext = await encrypt(rightKey, new Uint8Array([1, 2, 3]));

      await expect(decrypt(wrongKey, ciphertext)).rejects.toThrow();
    });

    it('handles empty plaintext', async () => {
      const alice = await generateKeyPair();
      const bob = await generateKeyPair();
      const key = await deriveSharedKey(alice.privateKey, bob.publicKey);

      const plaintext = new Uint8Array(0);
      const ciphertext = await encrypt(key, plaintext);
      const decrypted = await decrypt(key, ciphertext);

      expect(decrypted).toEqual(plaintext);
    });

    it('handles binary data with all byte values', async () => {
      const alice = await generateKeyPair();
      const bob = await generateKeyPair();
      const key = await deriveSharedKey(alice.privateKey, bob.publicKey);

      const plaintext = new Uint8Array(256);
      for (let i = 0; i < 256; i++) plaintext[i] = i;

      const ciphertext = await encrypt(key, plaintext);
      const decrypted = await decrypt(key, ciphertext);

      expect(decrypted).toEqual(plaintext);
    });
  });

  describe('cross-compatibility with Go implementation', () => {
    // Test vectors generated by internal/crypto/testvectors_test.go
    // using fixed X25519 private keys and a known nonce.
    const VECTORS = {
      alicePub: 'B6N8vBQgk8i3VdwbEOhstCY3StFqqFPtC9/AsrhtHHw=',
      bobPub: 'WGmv9FBUlzLLqu1eXfmzCm2jHLDldCutWtShp2jxpns=',
      aesKey: 'Wr2/eYJrpZVOtcYU2BuqxYhrQ7BxzwnphtZ1pncQ54U=',
      ciphertext: 'AAECAwQFBgcICQoLkOF9g4xG3K8NUeBl0qvSEhkzZfDVBcD265wd0Q==',
      plaintext: 'aGVsbG8ga2V5dHVu', // "hello keytun"
    };

    function b64ToUint8(b64) {
      const str = atob(b64);
      const bytes = new Uint8Array(str.length);
      for (let i = 0; i < str.length; i++) bytes[i] = str.charCodeAt(i);
      return bytes;
    }

    it('decrypts ciphertext produced by Go', async () => {
      // Import the AES key derived by Go's HKDF
      const aesKeyBytes = b64ToUint8(VECTORS.aesKey);
      const aesKey = await crypto.subtle.importKey(
        'raw',
        aesKeyBytes,
        { name: 'AES-GCM', length: 256 },
        false,
        ['encrypt', 'decrypt'],
      );

      const ciphertext = b64ToUint8(VECTORS.ciphertext);
      const decrypted = await decrypt(aesKey, ciphertext);
      const expected = b64ToUint8(VECTORS.plaintext);

      expect(decrypted).toEqual(expected);
      expect(new TextDecoder().decode(decrypted)).toBe('hello keytun');
    });
  });

  describe('decrypt validation', () => {
    it('rejects ciphertext shorter than nonce size', async () => {
      const alice = await generateKeyPair();
      const bob = await generateKeyPair();
      const key = await deriveSharedKey(alice.privateKey, bob.publicKey);

      const tooShort = new Uint8Array(11); // less than 12-byte nonce
      await expect(decrypt(key, tooShort)).rejects.toThrow();
    });

    it('rejects tampered ciphertext', async () => {
      const alice = await generateKeyPair();
      const bob = await generateKeyPair();
      const key = await deriveSharedKey(alice.privateKey, bob.publicKey);

      const ciphertext = await encrypt(key, new TextEncoder().encode('secret'));
      // Flip a byte in the ciphertext portion (after the nonce)
      ciphertext[15] ^= 0xff;

      await expect(decrypt(key, ciphertext)).rejects.toThrow();
    });
  });
});
